# Generated by Django 5.0.6 on 2024-06-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('sim1', models.FloatField()),
                ('sim2', models.FloatField()),
                ('sim3', models.FloatField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('vector', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
