# Generated by Django 5.0.6 on 2024-06-11 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfchatgpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='query',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='sim1',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='sim2',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='sim3',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatlog',
            name='ip',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
